# this file is *not* meant to cover or endorse the use of travis, but rather to
# help confirm pull requests to this project.

language: python
python: 2.7
sudo: false
branches:
  only:
    - master
env:
 - TOXENV=py27
install:
 - pip install -U tox twine wheel codecov
script: tox
after_success:
  - codecov
deploy:
provider: pypi
distributions: "sdist bdist_wheel"
user: scrapy
password:
  secure: JaAKcy1AXWXDK3LXdjOtKyaVPCSFoCGCnW15g4f65E/8Fsi9ZzDfmBa4Equs3IQb/vs/if2SVrzJSr7arN7r9Z38Iv1mUXHkFAyA3Ym8mThfABBzzcUWEQhIHrCX0Tdlx9wQkkhs+PZhorlmRS4gg5s6DzPaeA2g8SCgmlRmFfA=
on:
  tags: true
  all_branches: true
  repo: scrapy/scrapy
  condition: "$TOXENV == py27 && $TRAVIS_TAG =~ ^[0-9]+[.][0-9]+[.][0-9]+(rc[0-9]+)?$"
